import { useEffect, useState } from 'react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
async function post(path:string){const r=await fetch(`${API}${path}`,{method:'POST'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Request failed');return d;}
export default function Enhancer(){
 const [path,setPath]=useState(window.location.pathname),[open,setOpen]=useState(false),[size,setSize]=useState(10000),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const on=()=>setPath(window.location.pathname);window.addEventListener('popstate',on);const id=window.setInterval(on,500);return()=>{window.removeEventListener('popstate',on);window.clearInterval(id)}},[]);
 if(path!=='/simulation')return null;
 const run=async()=>{setBusy(true);setError('');try{setResult(await post(`/simulation/run-benchmark?dataset_size=${size}&seed=42`))}catch(e){setError(e instanceof Error?e.message:'Benchmark failed')}finally{setBusy(false)}};
 return <><button onClick={()=>setOpen(true)} style={{position:'fixed',right:32,top:76,zIndex:60,background:'#fff',border:'1px solid #c6c6cd',borderRadius:6,padding:'9px 14px',fontWeight:700,fontSize:13}}>Synthetic Benchmark</button>{open&&<div onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} style={{position:'fixed',inset:0,zIndex:100,background:'rgba(0,0,0,.25)',display:'flex',alignItems:'center',justifyContent:'center',padding:16}}><div style={{width:'100%',maxWidth:520,background:'#fff',border:'1px solid #c6c6cd',borderRadius:12,padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{margin:0}}>Configure Synthetic Benchmark</h2><button onClick={()=>setOpen(false)} style={{border:0,background:'transparent',fontSize:20}}>×</button></div><p style={{color:'#45464d',fontSize:13,lineHeight:1.6}}>Generate a controlled, reproducible cohort. This remains simulation-only.</p><label style={{display:'block',fontSize:12,fontWeight:700,marginTop:18}}>COHORT SIZE<input type="number" min={100} max={100000} value={size} onChange={e=>setSize(Number(e.target.value))} style={{display:'block',width:'100%',marginTop:6,height:40,border:'1px solid #c6c6cd',borderRadius:6,padding:'0 10px'}}/></label>{error&&<div style={{marginTop:14,color:'#93000a',background:'#ffdad6',padding:10,borderRadius:6,fontSize:12}}>{error}</div>}{result&&<div style={{marginTop:14,background:'#d9f7eb',color:'#006b4b',padding:12,borderRadius:6,fontSize:12}}>Evaluated {result.dataset_size?.toLocaleString()} transactions · RecoverAI recovered {result.revenue_recovered?.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0})} · {result.improvement_percentage}% improvement.</div>}<div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:20}}><button onClick={()=>setOpen(false)} style={{padding:'9px 14px',border:'1px solid #c6c6cd',background:'#fff',borderRadius:6,fontWeight:700}}>Close</button><button disabled={busy} onClick={()=>void run()} style={{padding:'9px 14px',border:0,background:'#0058be',color:'#fff',borderRadius:6,fontWeight:700}}>{busy?'Running…':'Run Benchmark'}</button></div></div></div>}</>;
}
